[2025-06-10T15:23:11.701+0200] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-06-10T15:23:11.705+0200] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: case2.wait_for_taxi_zone_file manual__2025-06-10T13:23:08.342516+00:00 [queued]>
[2025-06-10T15:23:11.706+0200] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: case2.wait_for_taxi_zone_file manual__2025-06-10T13:23:08.342516+00:00 [queued]>
[2025-06-10T15:23:11.707+0200] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-06-10T15:23:11.712+0200] {taskinstance.py:2890} INFO - Executing <Task(FileSensor): wait_for_taxi_zone_file> on 2025-06-10 13:23:08.342516+00:00
[2025-06-10T15:23:11.714+0200] {standard_task_runner.py:72} INFO - Started process 26957 to run task
[2025-06-10T15:23:11.717+0200] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'case2', 'wait_for_taxi_zone_file', 'manual__2025-06-10T13:23:08.342516+00:00', '--job-id', '21', '--raw', '--subdir', 'DAGS_FOLDER/case2.py', '--cfg-path', '/var/folders/sj/kmk_wl3517d377606n_z382h0000gp/T/tmp0kef2lv9']
[2025-06-10T15:23:11.719+0200] {standard_task_runner.py:105} INFO - Job 21: Subtask wait_for_taxi_zone_file
[2025-06-10T15:23:11.747+0200] {task_command.py:467} INFO - Running <TaskInstance: case2.wait_for_taxi_zone_file manual__2025-06-10T13:23:08.342516+00:00 [running]> on host LGLXN9TVJX
[2025-06-10T15:23:11.772+0200] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='case2' AIRFLOW_CTX_TASK_ID='wait_for_taxi_zone_file' AIRFLOW_CTX_EXECUTION_DATE='2025-06-10T13:23:08.342516+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-10T13:23:08.342516+00:00'
[2025-06-10T15:23:11.773+0200] {taskinstance.py:732} INFO - ::endgroup::
[2025-06-10T15:23:11.829+0200] {baseoperator.py:423} WARNING - FileSensor.execute cannot be called outside TaskInstance!
[2025-06-10T15:23:11.832+0200] {base.py:84} INFO - Retrieving connection 'fs_default'
[2025-06-10T15:23:11.833+0200] {filesystem.py:109} INFO - Poking for file /opt/airflow/data/raw/zones_13062025.csv
[2025-06-10T15:23:41.834+0200] {filesystem.py:109} INFO - Poking for file /opt/airflow/data/raw/zones_13062025.csv
[2025-06-10T15:24:11.838+0200] {filesystem.py:109} INFO - Poking for file /opt/airflow/data/raw/zones_13062025.csv
[2025-06-10T15:24:36.662+0200] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-06-10T15:24:36.685+0200] {process_utils.py:132} INFO - Sending 15 to group 26957. PIDs of all processes in the group: [26957]
[2025-06-10T15:24:36.685+0200] {process_utils.py:87} INFO - Sending the signal 15 to group 26957
[2025-06-10T15:24:36.686+0200] {taskinstance.py:3094} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-06-10T15:24:36.725+0200] {taskinstance.py:3095} ERROR - Stacktrace: 
  File "/Users/tsimsek/Library/Python/3.9/bin/airflow", line 8, in <module>
    sys.exit(main())
  File "/Users/tsimsek/Library/Python/3.9/lib/python/site-packages/airflow/__main__.py", line 62, in main
    args.func(args)
  File "/Users/tsimsek/Library/Python/3.9/lib/python/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/Users/tsimsek/Library/Python/3.9/lib/python/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/Users/tsimsek/Library/Python/3.9/lib/python/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/Users/tsimsek/Library/Python/3.9/lib/python/site-packages/airflow/cli/commands/task_command.py", line 254, in _run_task_by_selected_method
    return _run_task_by_local_task_job(args, ti)
  File "/Users/tsimsek/Library/Python/3.9/lib/python/site-packages/airflow/cli/commands/task_command.py", line 322, in _run_task_by_local_task_job
    ret = run_job(job=job_runner.job, execute_callable=job_runner._execute)
  File "/Users/tsimsek/Library/Python/3.9/lib/python/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/Users/tsimsek/Library/Python/3.9/lib/python/site-packages/airflow/jobs/job.py", line 421, in run_job
    return execute_job(job, execute_callable=execute_callable)
  File "/Users/tsimsek/Library/Python/3.9/lib/python/site-packages/airflow/jobs/job.py", line 450, in execute_job
    ret = execute_callable()
  File "/Users/tsimsek/Library/Python/3.9/lib/python/site-packages/airflow/jobs/local_task_job_runner.py", line 171, in _execute
    self.task_runner.start()
  File "/Users/tsimsek/Library/Python/3.9/lib/python/site-packages/airflow/task/task_runner/standard_task_runner.py", line 55, in start
    self.process = self._start_by_fork()
  File "/Users/tsimsek/Library/Python/3.9/lib/python/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/Users/tsimsek/Library/Python/3.9/lib/python/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/Users/tsimsek/Library/Python/3.9/lib/python/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/Users/tsimsek/Library/Python/3.9/lib/python/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/Users/tsimsek/Library/Python/3.9/lib/python/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/Users/tsimsek/Library/Python/3.9/lib/python/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/Users/tsimsek/Library/Python/3.9/lib/python/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/Users/tsimsek/Library/Python/3.9/lib/python/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
  File "/Users/tsimsek/Library/Python/3.9/lib/python/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/Users/tsimsek/Library/Python/3.9/lib/python/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/Users/tsimsek/Library/Python/3.9/lib/python/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/Users/tsimsek/Library/Python/3.9/lib/python/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/Users/tsimsek/Library/Python/3.9/lib/python/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
  File "/Users/tsimsek/Library/Python/3.9/lib/python/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/Users/tsimsek/Library/Python/3.9/lib/python/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/tsimsek/Library/Python/3.9/lib/python/site-packages/airflow/sensors/filesystem.py", line 123, in execute
    super().execute(context=context)
  File "/Users/tsimsek/Library/Python/3.9/lib/python/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/tsimsek/Library/Python/3.9/lib/python/site-packages/airflow/sensors/base.py", line 337, in execute
    time.sleep(self._get_next_poke_interval(started_at, run_duration, poke_count))
  File "/Users/tsimsek/Library/Python/3.9/lib/python/site-packages/airflow/models/taskinstance.py", line 3095, in signal_handler
    self.log.error("Stacktrace: \n%s", "".join(traceback.format_stack()))

[2025-06-10T15:24:36.728+0200] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/tsimsek/Library/Python/3.9/lib/python/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/Users/tsimsek/Library/Python/3.9/lib/python/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
  File "/Users/tsimsek/Library/Python/3.9/lib/python/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/Users/tsimsek/Library/Python/3.9/lib/python/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/tsimsek/Library/Python/3.9/lib/python/site-packages/airflow/sensors/filesystem.py", line 123, in execute
    super().execute(context=context)
  File "/Users/tsimsek/Library/Python/3.9/lib/python/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/tsimsek/Library/Python/3.9/lib/python/site-packages/airflow/sensors/base.py", line 337, in execute
    time.sleep(self._get_next_poke_interval(started_at, run_duration, poke_count))
  File "/Users/tsimsek/Library/Python/3.9/lib/python/site-packages/airflow/models/taskinstance.py", line 3097, in signal_handler
    raise AirflowTaskTerminated("Task received SIGTERM signal")
airflow.exceptions.AirflowTaskTerminated: Task received SIGTERM signal
[2025-06-10T15:24:36.729+0200] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=case2, task_id=wait_for_taxi_zone_file, run_id=manual__2025-06-10T13:23:08.342516+00:00, execution_date=20250610T132308, start_date=20250610T132311, end_date=20250610T132436
[2025-06-10T15:24:36.741+0200] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-06-10T15:24:36.782+0200] {process_utils.py:80} INFO - Process psutil.Process(pid=26957, status='terminated', exitcode=2, started='15:23:11') (26957) terminated with exit code 2
[2025-06-10T15:24:36.796+0200] {standard_task_runner.py:217} INFO - Process not found (most likely exited), stop collecting metrics
[2025-06-10T15:24:39.541+0200] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-06-10T15:24:39.544+0200] {taskinstance.py:2604} INFO - Dependencies not met for <TaskInstance: case2.wait_for_taxi_zone_file manual__2025-06-10T13:23:08.342516+00:00 [failed]>, dependency 'Task Instance State' FAILED: Task is in the 'failed' state.
[2025-06-10T15:24:39.545+0200] {local_task_job_runner.py:166} INFO - Task is not able to be run
